# Numpy Array
* Array
* Matrix
* Reshape
* Max
* Min
* argmax
* argmin
* Arange
* Zeros
* Ones
* Linespace
* Eye
* Random
* Random.rand
* Random.randint

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
ar = np.array(my_list)

In [4]:
ar

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
mat = np.array(my_mat)

In [7]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.16510979, 0.32635969, 0.01850735, 0.74263249, 0.18752876])

In [17]:
np.random.rand(5,5)

array([[0.44915305, 0.95381949, 0.14661938, 0.11694918, 0.53219679],
       [0.61575769, 0.85125813, 0.47852013, 0.66753818, 0.91881465],
       [0.63758347, 0.98079549, 0.56054611, 0.71370122, 0.52571369],
       [0.93212444, 0.47899264, 0.56047981, 0.28822693, 0.28233327],
       [0.36011109, 0.53962814, 0.05340089, 0.88861609, 0.16049186]])

In [18]:
np.random.randn(2)

array([-0.02002867, -0.69817505])

In [19]:
np.random.randn(4,4)

array([[ 1.43068432,  0.08814541, -0.80099797,  0.90452622],
       [-2.04371266, -1.06076529,  1.20546265, -0.20720312],
       [-0.09657997, -0.19255112,  0.61760386, -1.93072478],
       [-0.08674058, -0.74920995, -1.55306137,  1.83840048]])

In [20]:
np.random.randint(1,100)

96

In [21]:
np.random.randint(1,100,10)

array([93, 56, 93, 41, 45, 47,  5, 38, 94, 71])

In [22]:
rarr = np.random.randint(0,50,10)

In [23]:
rarr

array([38,  4, 17, 11, 15, 27, 37,  8, 40, 41])

In [24]:
arr = np.arange(0,50)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [26]:
arr.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [27]:
rarr.max()

41

In [28]:
rarr.min()

4

In [29]:
rarr.argmax()

9

In [30]:
rarr.argmin()

1

In [31]:
arr.shape

(50,)

In [32]:
arr.dtype

dtype('int32')

In [33]:
from numpy.random import randint

In [34]:
randint(0,30)

12

# Numpy Indexing And Selection
* Slicing with 1D Array
* Slicing with 2D Array

In [41]:
ar = np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
ar[8]

8

In [43]:
ar[1:5]

array([1, 2, 3, 4])

In [44]:
ar[:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
ar[5:]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
ar[0:5] = 100
ar

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
ar = np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
slice_of_ar = ar[0:6]
slice_of_ar

array([0, 1, 2, 3, 4, 5])

In [51]:
slice_of_ar[:]

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_of_ar[:] = 99
slice_of_ar

array([99, 99, 99, 99, 99, 99])

In [54]:
ar

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
ar_copy = ar.copy()
ar_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
ar_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
ar_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
ar_2d[0][1]

10

In [61]:
ar_2d[0]

array([ 5, 10, 15])

In [62]:
ar_2d[1,2]

30

In [63]:
ar_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [64]:
ar_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [66]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [72]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [74]:
ar_2d = np.arange(50).reshape(5,10)
ar_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [75]:
ar_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Numpy Operation
* Array with Array
* Array with Scalars
* Universal Array Functions

In [77]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [80]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [84]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [85]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [86]:
arr / arr

C:\Users\akshay\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [87]:
1 / arr

C:\Users\akshay\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [88]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [89]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [90]:
np.max(arr)

10

In [91]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [92]:
np.log(arr)

C:\Users\akshay\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])