In [1]:
import numpy as np

In [2]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
arr * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [23]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [25]:
ar_2d = np.arange(0,9).reshape(3,3)
ar_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.random.rand()

0.38272881463915465

In [38]:
np.random.randn(25)

array([ 1.09068703, -0.18203447, -2.0335401 ,  0.39908264, -0.31173255,
        1.21268321, -0.33417936, -1.02737742, -0.94816006,  0.20186603,
        0.2707846 ,  0.76922604, -1.22393435, -0.67921335,  0.08948561,
        0.72323007, -0.63689139,  0.98094179,  1.14367305, -1.22542849,
       -2.13413742,  1.0108213 ,  0.37406838, -1.70751219, -0.78704022])

In [43]:
np.random.randn(10,10)

array([[-0.06097113,  0.9026962 ,  1.16741966, -1.48070744,  0.01336605,
         0.55789268,  1.20477069, -0.40672043, -1.24152344, -0.08452393],
       [ 0.53355859,  0.32119794,  1.01501182,  1.20445213,  0.51432357,
         0.01001926, -0.37992176, -0.77743567, -0.62017638,  1.07666603],
       [-1.26386858, -0.11458194,  1.55191191,  1.64270047, -0.47728953,
         0.64012777,  0.95345266,  1.2866107 ,  1.04006877, -1.22868125],
       [-2.2084332 ,  0.37183758,  0.68009181,  0.19718818,  0.88403875,
        -1.15110778, -1.49292108,  0.35919412, -1.53914043,  0.21719539],
       [-0.65850743,  0.66334899,  2.11941533, -0.19370084,  1.40601591,
        -1.40665028, -2.21248904, -0.34180297, -1.19644708, -0.58674141],
       [-0.75613167, -0.18326937, -0.00912229,  1.10468678,  0.72076869,
         1.61866468, -0.79174143,  1.35812933, -0.45074824,  0.73389645],
       [-0.2328641 , -0.20216532, -1.54134006,  0.93396227,  1.98501509,
         1.22320291,  0.25821197,  0.21378405

In [44]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [45]:
np.sum(arr)

1230

In [47]:
np.sum(ar_2d[:])

36